### ISSUE TITLE
Enhance front end workflow

### ISSUE THREAD

**Issue by michieldewilde** [nicoverbruggen/openshowcase#12]
Using browserify and gulp to make writing javascript and scss enjoyable. How do you convert sass files to css?

**Comment by nicoverbruggen** [comment]
I just used PhpStorm's built in sass watcher during the development of openshowcase. 

Possible approach: https://gist.github.com/nicoverbruggen/b3894dd1d5bc049a2cc1

**Comment by michieldewilde** [comment]
Not all of use. Should bower be included into the git repo? I always use bower.json and then let them do bower install.

**Comment by nicoverbruggen** [comment]
No, it shouldn't. But since I was just working solo on this one, I never bothered to clean it up.
Are you interested in working on this? 

I definitely want to do the following things:

1) clean up front-end (set up gulp and the like)
2) add more tests
3) fix pending issues
4) change version numbering (inconsequential at the moment)

But I don't have much spare time to do this all immediately, though.

**Comment by michieldewilde** [comment]
I'm going to start with cleaning up the front-end.

**Comment by nicoverbruggen** [comment]
:+1: 

Make sure to update the readme, and feel free to send a pull request :)

**Comment by michieldewilde** [comment]
sure
